#pragma once
const int MAX_USERNAME_SIZE = 12;
const int MAX_PASSWORD_SIZE = 16;
const int MIN_USERNAME_SIZE = 5;
const int MIN_PASSWORD_SIZE = 7;
const int MAX_DIR_SIZE = 50;
const char DIR_DRAWING[] = "files/Drawings";
const char DIR_SOLUTION[] = "files/Levels";
const char DIR_LAST_ATTEPMTS[] = "files/LastAttempts";
const char LIST_OF_LEVELS[10][10] = { "Beginner1","Beginner2", "Easy1","Easy2","Medium1","Medium2" ,"Hard1" ,"Hard2","Expert1","Expert2" };
char** drawing;
char** solution;
char* logged;
char* level;
char* difficulty;
int columns = -1;
int rows = -1;
int countOfLives = -1;
int rowIndex = -1;
int colIndex = -1;
int matrixSize = -1;
